version: '3'
services:
  node:
    image: maheshagiratech/kube
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/code
    links:
           - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
