apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: node-claim0
  name: node-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
